/**
 * 실행: npx tsx src/pages/parent/parentHubHomeLayout.test.ts
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const home = readFileSync('src/pages/parent/ParentStudentHomePage.tsx', 'utf8')
const grid = readFileSync('src/components/parent/ParentCategoryGrid.tsx', 'utf8')
const navItems = readFileSync('src/components/parent/parentNavItems.ts', 'utf8')
const layout = readFileSync('src/components/layout/ParentStudentLayout.tsx', 'utf8')
const sidebar = readFileSync('src/components/parent/ParentStudentSidebar.tsx', 'utf8')
const bottomNav = readFileSync('src/components/parent/ParentStudentBottomNav.tsx', 'utf8')
const teacherHome = readFileSync('src/pages/teacherMobile/TeacherMobileDashboardPage.tsx', 'utf8')
const hubHome = readFileSync('src/hub/HubHomePage.tsx', 'utf8')
const dashboard = readFileSync('src/pages/DashboardPage.tsx', 'utf8')
const push = readFileSync('src/components/parent/ParentPushOptIn.tsx', 'utf8')
const todayReport = readFileSync('src/pages/parent/ParentStudentTodayReportPage.tsx', 'utf8')
const weekly = readFileSync('src/pages/parent/ParentStudentWeeklySummaryPage.tsx', 'utf8')

assert.match(home, /학부모 허브/)
assert.match(home, /HYPER ACADEMY/)
assert.match(home, /HUB_ACADEMY_LOGO_WEBP/)
assert.match(home, /className="hub-hero"/)
assert.match(home, /max-w-lg px-3/)
assert.match(home, /ParentCategoryGrid/)
assert.match(home, /ParentInstallGuide studentAccessKey=\{student\.studentAccessKey\}/)
assert.match(home, /ParentPushOptIn/)
assert.match(home, /aria-label="메뉴 열기"/)
assert.doesNotMatch(home, /ParentStudentInfoCard/)

assert.match(grid, /hub-menu-grid grid grid-cols-3/)
assert.match(grid, /className="hub-tile"/)
assert.match(grid, /className="hub-feature-card"/)
assert.match(grid, /parentTodayReportItem/)
assert.match(grid, /출결 · 진도 · 숙제/)
assert.match(grid, /일일테스트 · 수업태도/)
assert.match(grid, /hasUnreadWeeklySummary/)
assert.match(grid, /hasUnreadAdmissionStrategyMaterials/)
assert.match(grid, /parent-hub-unread/)
assert.match(grid, /weekly-learning-summary/)
assert.match(grid, /admission-strategy/)
assert.doesNotMatch(grid, /pm-featured-card/)
assert.doesNotMatch(grid, /grid-cols-2/)

assert.match(navItems, /label: '주간 SUMMARY'/)
assert.match(navItems, /label: '월간 학습진단'/)
assert.match(navItems, /label: '월말평가'/)
assert.match(navItems, /label: '공지·보강'/)
assert.match(navItems, /label: '입시전략'/)
assert.match(navItems, /label: '질문하기'/)
assert.match(navItems, /segment: 'notices-makeup'/)
assert.match(navItems, /segment: 'monthly-learning-report'/)
assert.match(navItems, /label: '공지사항 · 보강계획'/)

assert.match(layout, /openParentMenu/)
assert.match(layout, /ParentStudentSidebar/)
assert.match(layout, /ParentPwaRegistrar/)
assert.doesNotMatch(layout, /ParentStudentBottomNav/)
assert.match(sidebar, /parentSidebarItems/)
assert.match(sidebar, /ParentPushOptIn/)
assert.match(bottomNav, /진단REPORT/)
assert.match(bottomNav, /Today Report/)

assert.match(teacherHome, /강사 허브/)
assert.match(teacherHome, /Today Report 입력/)
assert.doesNotMatch(teacherHome, /학부모 허브/)
assert.match(hubHome, /학습 허브/)
assert.match(hubHome, /My Study Plan/)
assert.doesNotMatch(hubHome, /학부모 허브/)
assert.match(dashboard, /HYPER STUDENT CARE/)
assert.doesNotMatch(dashboard, /hub-hero/)
assert.match(push, /data-parent-push-opt-in/)
assert.match(todayReport, /ParentStudentTodayReportPage/)
assert.match(weekly, /ParentStudentWeeklySummaryPage/)

console.log('parentHubHomeLayout.test.ts passed')
