/**
 * 실행: npx tsx src/pages/parent/parentHubHomeLayout.test.ts
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const home = readFileSync('src/pages/parent/ParentStudentHomePage.tsx', 'utf8')
const grid = readFileSync('src/components/parent/ParentCategoryGrid.tsx', 'utf8')
const navItems = readFileSync('src/components/parent/parentNavItems.ts', 'utf8')
const layout = readFileSync('src/components/layout/ParentStudentLayout.tsx', 'utf8')
const sidebar = readFileSync('src/components/parent/ParentStudentSidebar.tsx', 'utf8')
const bottomNav = readFileSync('src/components/parent/ParentStudentBottomNav.tsx', 'utf8')
const teacherHome = readFileSync('src/pages/teacherMobile/TeacherMobileDashboardPage.tsx', 'utf8')
const hubHome = readFileSync('src/hub/HubHomePage.tsx', 'utf8')
const dashboard = readFileSync('src/pages/DashboardPage.tsx', 'utf8')
const push = readFileSync('src/components/parent/ParentPushOptIn.tsx', 'utf8')
const todayReport = readFileSync('src/pages/parent/ParentStudentTodayReportPage.tsx', 'utf8')
const weekly = readFileSync('src/pages/parent/ParentStudentWeeklySummaryPage.tsx', 'utf8')
const parentTheme = readFileSync('src/styles/parentMobileTheme.css', 'utf8')
const teacherTheme = readFileSync('src/styles/teacherMobileTheme.css', 'utf8')
const hubCss = readFileSync('src/hub/hub.css', 'utf8')

assert.match(home, /학부모 허브/)
assert.match(home, /HYPER ACADEMY/)
assert.match(home, /HUB_ACADEMY_LOGO_WEBP/)
assert.match(home, /className="hub-hero"/)
assert.match(home, /max-w-lg px-3/)
assert.match(home, /ParentCategoryGrid/)
assert.match(home, /ParentInstallGuide studentAccessKey=\{student\.studentAccessKey\}/)
assert.match(home, /ParentPushOptIn/)
assert.match(home, /aria-label="메뉴 열기"/)
assert.doesNotMatch(home, /ParentStudentInfoCard/)

assert.match(grid, /hub-menu-grid grid grid-cols-3/)
assert.match(grid, /className="hub-tile"/)
assert.match(grid, /className="hub-feature-card"/)
assert.match(grid, /parentTodayReportItem/)
assert.match(grid, /출결 · 진도 · 숙제/)
assert.match(grid, /일일테스트 · 수업태도/)
assert.match(grid, /hasUnreadWeeklySummary/)
assert.match(grid, /hasUnreadAdmissionStrategyMaterials/)
assert.match(grid, /parent-hub-unread/)
assert.match(grid, /hasUnreadParentSuggestions/)
assert.match(grid, /hasUnreadNoticesOrMakeup/)
assert.match(grid, /weekly-learning-summary/)
assert.match(grid, /admission-strategy/)
assert.match(grid, /notices-makeup/)
assert.doesNotMatch(grid, /pm-featured-card/)
assert.doesNotMatch(grid, /grid-cols-2/)

assert.match(navItems, /label: '주간 SUMMARY'/)
assert.match(navItems, /월간 학습진단/)
assert.match(navItems, /월말평가 결과/)
assert.match(navItems, /label: '입시전략'/)
assert.match(navItems, /label: '질문하기'/)
assert.match(navItems, /label: '건의사항'/)
assert.match(navItems, /label: '시간표'/)
assert.match(navItems, /주간 수학 오답/)
assert.match(navItems, /영어 단어 누적/)
assert.match(navItems, /segment: 'notices-makeup'/)
assert.match(navItems, /segment: 'monthly-learning-report'/)
assert.match(navItems, /segment: 'questions'/)
assert.match(navItems, /segment: 'suggestions'/)
assert.match(navItems, /segment: 'weekly-wrong-vocab'/)
assert.match(navItems, /segment: 'schedule'/)
assert.match(navItems, /label: '공지사항 · 보강계획'/)
assert.match(navItems, /label: '공지사항\\n보강계획'/)
assert.doesNotMatch(navItems, /label: '공지·보강'/)

assert.match(layout, /openParentMenu/)
assert.match(layout, /ParentStudentSidebar/)
assert.match(layout, /ParentPwaRegistrar/)
assert.match(layout, /ParentUnreadProvider/)
assert.doesNotMatch(layout, /ParentStudentBottomNav/)
assert.match(sidebar, /parentSidebarItems/)
assert.match(sidebar, /ParentPushOptIn/)
assert.match(bottomNav, /진단REPORT/)
assert.match(bottomNav, /Today Report/)

assert.match(teacherHome, /강사 허브/)
assert.match(teacherHome, /Today Report 입력/)
assert.doesNotMatch(teacherHome, /학부모 허브/)
assert.match(hubHome, /학습 허브/)
assert.match(hubHome, /My Study Plan/)
assert.doesNotMatch(hubHome, /학부모 허브/)
assert.match(dashboard, /HYPER STUDENT CARE/)
assert.doesNotMatch(dashboard, /hub-hero/)
assert.match(push, /data-parent-push-opt-in/)
assert.match(todayReport, /ParentStudentTodayReportPage/)
assert.match(weekly, /ParentStudentWeeklySummaryPage/)

assert.match(parentTheme, /\.parent-mobile-app \.parent-hub-home \.hub-tile/)
assert.match(parentTheme, /min-height: 8rem/)
assert.match(parentTheme, /-webkit-line-clamp: 3/)
assert.match(parentTheme, /\.parent-mobile-app \.parent-hub-home \.parent-home/)
assert.match(parentTheme, /padding-bottom: max\(1\.25rem, env\(safe-area-inset-bottom, 0px\)\)/)
assert.match(parentTheme, /\.parent-mobile-app \.parent-hub-home \.hub-feature-card/)
assert.match(parentTheme, /min-height: 6\.5rem/)
assert.doesNotMatch(parentTheme, /min-height: 5\.15rem/)
assert.doesNotMatch(parentTheme, /min-height: 5\.9rem/)
assert.match(parentTheme, /\.parent-mobile-app \.parent-hub-home \.hub-hero \{/)
assert.match(parentTheme, /padding: 0\.95rem 1\.05rem 1rem/)
assert.match(hubCss, /min-height: 6\.4rem/)
assert.match(hubCss, /min-height: 4\.7rem/)
assert.doesNotMatch(hubCss, /\.parent-hub-home \.hub-tile/)
assert.doesNotMatch(hubCss, /min-height: 6\.5rem/)
assert.match(teacherTheme, /\.teacher-mobile-app \.teacher-hub-home \.hub-feature-card/)
assert.match(teacherTheme, /min-height: 5rem/)
assert.doesNotMatch(teacherTheme, /min-height: 6\.5rem/)
assert.match(push, /placement === 'sidebar'/)
assert.match(push, /pm-card mt-3 px-3 py-2\.5/)
assert.match(push, /알림 설정/)
assert.doesNotMatch(navItems, /주간 오답현황/)
assert.match(navItems, /건의사항/)
assert.doesNotMatch(home, /주간 오답현황/)

console.log('parentHubHomeLayout.test.ts passed')
