/**
 * 실행: npx tsx src/hub/hubWebPushV1.test.ts
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const sql = readFileSync('supabase/hub-web-push-v1-migration.sql', 'utf8')
const edge = readFileSync('supabase/functions/send-hub-push-notification/index.ts', 'utf8')
const weekly = readFileSync('supabase/functions/generate-weekly-summaries/index.ts', 'utf8')
const parentClient = readFileSync('src/lib/parentPushClient.ts', 'utf8')
const parentRpc = readFileSync('src/lib/db/parentPushRpc.ts', 'utf8')
const parentOptIn = readFileSync('src/components/parent/ParentPushOptIn.tsx', 'utf8')
const todayReport = readFileSync('src/lib/todayReportCompletion.ts', 'utf8')
const careSw = readFileSync('public/care/sw.js', 'utf8')
const hubSw = readFileSync('public/hub/sw.js', 'utf8')
const teacherHandlers = readFileSync('public/teacher/push-handlers.js', 'utf8')
const vite = readFileSync('vite.config.ts', 'utf8')
const questions = readFileSync('src/hub/HubQuestionsPage.tsx', 'utf8')
const requests = readFileSync('src/hub/HubMaterialRequestPage.tsx', 'utf8')
const suggestions = readFileSync('src/hub/HubSuggestionsPage.tsx', 'utf8')
const weeklyPage = readFileSync('src/hub/HubWeeklyPage.tsx', 'utf8')
const teacherCms = readFileSync('src/pages/teacher/TeacherStudentHubPage.tsx', 'utf8')
const dataHook = readFileSync('src/hooks/useData.tsx', 'utf8')
const home = readFileSync('src/hub/HubHomePage.tsx', 'utf8')
const more = readFileSync('src/pages/teacherMobile/TeacherMobileMorePage.tsx', 'utf8')
const sidebar = readFileSync('src/components/Sidebar.tsx', 'utf8')
const envExample = readFileSync('.env.example', 'utf8')

assert.match(sql, /CREATE TABLE IF NOT EXISTS public\.student_push_subscriptions/)
assert.match(sql, /CREATE TABLE IF NOT EXISTS public\.teacher_push_subscriptions/)
assert.match(sql, /CREATE TABLE IF NOT EXISTS public\.hub_push_deliveries/)
assert.match(sql, /student:weekly:' \|\| student_id/)
assert.doesNotMatch(sql, /ALTER TABLE public\.parent_push_subscriptions/)
assert.doesNotMatch(sql, /UPDATE public\.parent_push_subscriptions/)
assert.doesNotMatch(sql, /INSERT INTO public\.parent_push_subscriptions/)
assert.doesNotMatch(sql, /DROP TABLE/)
assert.doesNotMatch(sql, /TRUNCATE/)
assert.match(sql, /a\.student_id IS NULL OR s\.id = a\.student_id/)
assert.match(sql, /NOTIFY pgrst, 'reload schema'/)
assert.match(edge, /send-hub-push-notification|web-push/)
assert.match(edge, /teacher:question/)
assert.match(edge, /teacher:inbox/)
assert.match(edge, /student:assignment/)
assert.match(edge, /student:inbox/)
assert.match(edge, /student:question/)
assert.match(edge, /student:notice/)
assert.match(edge, /student:weekly/)
assert.match(edge, /status === 404 \|\| status === 410/)
assert.match(edge, /새로운 학생 질문이 등록되었습니다/)
assert.match(edge, /오늘의 과제가 등록되었습니다/)
assert.doesNotMatch(edge, /VITE_SUPABASE_SERVICE_ROLE/)
assert.match(weekly, /send-hub-push-notification/)
assert.match(weekly, /weekly_summary_scan/)
assert.match(parentClient, /PARENT_SW_SCOPE = '\/care\/'/)
assert.match(parentRpc, /upsert_parent_push_subscription/)
assert.match(parentOptIn, /subscribeParentPush/)
assert.match(todayReport, /send-parent-report-notification/)
assert.match(careSw, /오늘 학습보고가 등록되었습니다/)
assert.match(hubSw, /addEventListener\('push'/)
assert.match(hubSw, /addEventListener\('notificationclick'/)
assert.match(teacherHandlers, /\/teacher\/mobile\/questions|\/teacher\/mobile/)
assert.match(vite, /importScripts: \['\/teacher\/push-handlers\.js'\]/)
assert.match(questions, /student_question_created/)
assert.match(requests, /student_inbox_created/)
assert.match(suggestions, /student_inbox_created/)
assert.match(weeklyPage, /weekly_summary_scan/)
assert.match(teacherCms, /assignment_saved/)
assert.match(teacherCms, /inbox_replied/)
assert.match(dataHook, /question_answered/)
assert.match(dataHook, /notice_saved/)
assert.match(dataHook, /notifyHubPush/)
assert.match(home, /StudentPushOptIn/)
assert.match(more, /TeacherPushOptIn/)
assert.match(sidebar, /TeacherPushOptIn/)
assert.match(envExample, /VITE_VAPID_PUBLIC_KEY/)
assert.doesNotMatch(envExample, /VAPID_PRIVATE_KEY=/)

console.log('hubWebPushV1 tests passed')
