/**
 * 실행: npx tsx src/hub/studentHubFollowup.test.ts
 */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const sql = readFileSync('supabase/student-hub-followup-migration.sql', 'utf8')
const v1 = readFileSync('supabase/student-learning-hub-v1-migration.sql', 'utf8')
const teacherCms = readFileSync('src/pages/teacher/TeacherStudentHubPage.tsx', 'utf8')
const teacherRepo = readFileSync('src/hub/teacherHubRepo.ts', 'utf8')
const hubRpc = readFileSync('src/hub/hubRpc.ts', 'utf8')
const requestPage = readFileSync('src/hub/HubMaterialRequestPage.tsx', 'utf8')
const suggestionPage = readFileSync('src/hub/HubSuggestionsPage.tsx', 'utf8')
const inboxThread = readFileSync('src/hub/HubInboxThread.tsx', 'utf8')
const parentWeekly = readFileSync('src/pages/parent/ParentStudentWeeklySummaryPage.tsx', 'utf8')
const hubWeekly = readFileSync('src/hub/HubWeeklyPage.tsx', 'utf8')
const scoring = readFileSync('src/utils/studentCare/weeklySummary.ts', 'utf8')
const constants = readFileSync('src/utils/studentCare/constants.ts', 'utf8')
const assignmentPage = readFileSync('src/hub/HubAssignmentsPage.tsx', 'utf8')

assert.doesNotMatch(sql, /TRUNCATE TABLE/i)
assert.doesNotMatch(sql, /DROP TABLE/i)
assert.doesNotMatch(sql, /CREATE OR REPLACE FUNCTION public\.get_parent_care_bundle/)
assert.doesNotMatch(sql, /CREATE OR REPLACE FUNCTION public\.submit_parent_question/)
assert.doesNotMatch(sql, /CREATE OR REPLACE FUNCTION public\.get_student_hub_bundle/)
assert.doesNotMatch(sql, /CREATE OR REPLACE FUNCTION public\.get_student_hub_identity/)
assert.match(sql, /ADD COLUMN IF NOT EXISTS teacher_reply/)
assert.match(sql, /ADD COLUMN IF NOT EXISTS teacher_replied_at/)
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.list_student_hub_inbox\(p_access_key text\)/)
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.update_student_hub_inbox/)
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.delete_student_hub_inbox/)
assert.match(sql, /CREATE OR REPLACE FUNCTION public\.get_student_hub_daily_tests/)
assert.match(sql, /WHERE i\.student_id = v_student_id/)
assert.match(sql, /WHERE id = p_id AND student_id = v_student_id/)
assert.match(sql, /WHERE t\.student_id = v_student_id/)
assert.match(sql, /GRANT EXECUTE ON FUNCTION public\.list_student_hub_inbox\(text\) TO anon/)
assert.match(sql, /GRANT EXECUTE ON FUNCTION public\.get_student_hub_daily_tests\(text\) TO anon/)
assert.match(v1, /AND a\.student_id IS NULL/)

assert.match(teacherCms, /label: '오늘의 과제'/)
assert.match(teacherCms, /teacherSaveAssignment/)
assert.match(teacherCms, /teacherReplyInbox/)
assert.match(teacherCms, /답변 저장/)
assert.match(teacherRepo, /teacher_reply/)
assert.match(hubRpc, /list_student_hub_inbox/)
assert.match(hubRpc, /update_student_hub_inbox/)
assert.match(hubRpc, /delete_student_hub_inbox/)
assert.match(hubRpc, /get_student_hub_daily_tests/)
assert.match(requestPage, /HubInboxThread/)
assert.match(suggestionPage, /HubInboxThread/)
assert.match(inboxThread, /rpcUpdateHubInbox/)
assert.match(inboxThread, /rpcDeleteHubInbox/)
assert.match(inboxThread, /강사 답변/)
assert.match(assignmentPage, /오늘 등록된 과제가 없습니다/)
assert.match(parentWeekly, /DailyTestWeeklyFlowCard/)
assert.match(parentWeekly, /dailyTests/)
assert.match(hubWeekly, /WeeklySummaryDetail/)
assert.match(hubWeekly, /rpcGetStudentHubDailyTests/)
assert.match(hubWeekly, /dailyTests={dailyTests}/)
assert.match(hubWeekly, /studentId={student.id}/)
assert.match(constants, /ATTENDANCE_WEEKLY_MAX = 20/)
assert.match(constants, /MATERIAL_WEEKLY_MAX = 10/)
assert.match(constants, /HOMEWORK_WEEKLY_MAX = 25/)
assert.match(constants, /DAILY_TEST_WEEKLY_MAX = 30/)
assert.match(constants, /ATTITUDE_WEEKLY_MAX = 15/)
assert.match(constants, /WEEKLY_SUMMARY_TOTAL_MAX = 100/)
assert.match(scoring, /DAILY_TEST_WEEKLY_MAX/)
assert.doesNotMatch(sql, /weekly_learning_summaries/)
assert.doesNotMatch(sql, /ATTENDANCE_WEEKLY_MAX/)

console.log('studentHubFollowup.test.ts passed')
